// ==UserScript==
// @name         能不能好好说话
// @namespace    https://lab.magiconch.com/nbnhhsh
// @version      0.1
// @description  首字母缩写划词翻译工具
// @author       itorr
// @match        https://weibo.com/*
// @grant        none
// ==/UserScript==

// !!! WARNING !!!
// This file IS GENERATED BY $ npm run build, DO NOT EDIT BY HAND!
